server:
  port: 8989
  context-path: /springboot
  jsp-servlet:
    init-parameters:
      development: true
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    type: org.apache.commons.dbcp.BasicDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
  http:
    encoding:
      charset: UTF-8
      force: true
mybatis:
  mapper-locations: classpath:/com/baixue/mapper/*DaoMapper.xml
  type-aliases-package: com.baixue.entity






